baseURL = ''

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "blog@aleguy02.dev"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# whether to use git commit log
enableGitInfo = true

# Author config
  [params.author]
    name = "Alejandro Villate"

# Header config
  [params.header]
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      pre = "blog @"
      # title name
      name = "aleguy02.dev"

# Social config about the author
  [params.social]
    GitHub = "aleguy02"
    Linkedin = "alejandrovillate1"
    Youtubechannel = "UCZbAl-d58jWJ_q5TFSJJYiA"

 # LoveIt CHANGED | 0.2.0 Page global config
  [params.page]
    [params.page.share]
      enable = true
      X = false
      Threads = false
      Facebook = false
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Diaspora = false # LoveIt NEW | 0.3.1
      Mix = false
      Telegram = false # LoveIt NEW | 0.3.1

  # LoveIt NEW | 0.2.5 TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    # My average typing speed is 80 wpm, so I did the math to find the speed here
    speed = 150
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 2500
    # character used for the cursor (HTML format is supported)
    cursorChar = "."
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1
  
  # Home page profile
    [params.home.profile]
      enable = true
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Hello world"
      # whether to use typeit animation for subtitle
      typeit = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      # disclaimer = "I like writing about what I'm learning"
